#!/bin/bash
echo ''
echo 'Format code and import'
fileArr=()
for path in `go list ./... | grep -v vendor`; do
    newPath=${GOPATH}/src/${path}
    checkPath=${path}/vendor/
    if [ -d ${newPath}/vendor ]; then
        if [ ${#fileArr[@]} = 0 ]; then
            set fileArr[${#fileArr[@]}] = ${checkPath}
        else
            for item in fileArr; do
            if [ ${item} = ${checkPath} ]; then
                break
            fi
            done
            set fileArr[${#fileArr[@]}] = ${checkPath}
        fi
        continue
    fi
    gofmt -w ${newPath}
    goimports -w ${newPath}
done
for item in ${fileArr[*]}; do
    change=`echo ${item} | sed 's#\/#\\\/#g'`
    sed -i 's/'"${change}"'//g' `find ./ -type f |grep -v vendor/ |grep -v .git |grep -v Godeps/`
done

echo ''
echo 'Go vet `go list ./... |grep -v vendor`'
go vet `go list ./... |grep -v vendor`

echo ''
echo 'Golint ./... |grep -v vendor'
golint ./... |grep -v vendor

echo ''
echo 'Go build'
go build

echo ''
echo 'Check go all jobs done!!!'
echo ''
